### ISSUE TITLE
File not downloading

### ISSUE THREAD

**Issue by uxpanel** [nimafanniasl/Terminal_DL#1]
I tried to download a .zip file with this and I got these errors:

```
Traceback (most recent call last):
  File "/home/jacob/bin/Terminal_DL/Main.py", line 128, in <module>
    Terminal_DL = FileDownloader()
  File "/home/jacob/bin/Terminal_DL/Main.py", line 34, in __init__
    self.notify_send("[INFO]: Download Started.")
  File "/home/jacob/bin/Terminal_DL/Main.py", line 80, in notify_send
    run(["notify-send", str(msg)])
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send'

```

**Comment by nimafanniasl** [comment]
What Distro Do You Have?
